### ISSUE TITLE
Model Changes Part 2

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#302]
- [x] add `external_id` fields to all models found in accounts, cluster, core, indicator, partner, and unicef 

- [x] `alternate_title` defined twice in `Partner` model - remove one of them -SC- Don't see twice?

- [x] move `funds_received_to_date` from `ProgressReport` to `ProgrammeDocument` model (this is info about the PD that will be synced from PMP

- [x] add a `funds_received_to_date_currency` in `ProgrammeDocument` model  -SC- Isn't this the same as above `funds_received_to_date` field?

- [x] Relationship between `ProgrammeDocument` and `CountryProgrammeOutput` should be M2M -SC- don't think so.... CP_output has a FK To PD. So 1 PD can have many CPO's, but CPO's are unique to a PD afaik? See in eTools code... Result is same as CPO I think? https://github.com/unicef/etools/blob/edece6dc02136c79463c26819f957449d1a2c063/EquiTrack/reports/models.py#L156 and https://github.com/unicef/etools/blob/edece6dc02136c79463c26819f957449d1a2c063/EquiTrack/partners/models.py#L1682 -SC- being done in #325

- [x] Change field name from `indicator` to `cp_output` in `LowerLevelOutput` model (misleading name)

- [x] `Reportable` and `Disaggregation` should have M2M relationship (related to #244) -SC- done in #244 already.

- [x] `cs_dates` fields in `ProgrammeDocument` and `Reportable` should support ability to set the `start_date`, `end_date` and `due_date` fields for multiple reports

- [x] **TO CHECK** currently `overall_status` available on `IndicatorReport`. In IP Reporting, `overall_status` is set at llo level. Does this currently assign all associated indicator reports to the same overall status?

- [x] **TO CHECK** what happens to the `report_status` of IndicatorReports associated to a ProgressReport when the `report_status` of the ProgressReport changes? Ideal behaviour is that the indicatorReports either have the `report_status` of the ProgressReport copied over from the ProgressReport. (will make running #316 more straightforward)

- [x] user = models.ForeignKey('account.User', related_name="clusters") on Cluster model doesn't make much sense?

- [x] Remove the locations m2m on Workspace

**Comment by chachra** [comment]
@kasfaw Can you please review my notes above with -SC- in them.. Thanks.

**Comment by kasfaw** [comment]
- 'Alternate_title' showed twice but @dfryta might have removed already
- there is a 'funds_recieved-date' AND 'funds_recieved_date_currency' fields needed in PD model
- CPOs are actually unique to a workspace (a UNICEF country office) not to a PD. Multiple PDs will be linked to the same CPO in a workspace. I would use the 'external_date' to check duplication during PD sync
-
