### ISSUE TITLE
Misc. IP reporting changes from change requests doc. (minor)

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#377]
- [ ] ~1> Display of the text on the blue bar must be changed from the actual name of PD Output to as per the text displayed in PMP. #frontend~ moved to #448

- [x] 2> Default view of the PD page should contain Signed, Active, and Suspended. Make status be multi-select and post to backend. Might require backend change to support multiple statuses as well. This should be achieved by having the list pre-filtered with the PD/SSFA Status filter. #backend #frontend

- [ ] 3> ~Include Signed/Active/Ended/Closed/Suspended/Terminated PDs in PRP so partner can report on them. Signed or Closed PD’s would not be reported on, just displayed. #backend~ moved to #448

- [x] 4> Remove population focus of PD / SSFA details card, from ui and data model. #backend #frontend

- [x] 5> Date format to the correct format i.e. (DD-MMM-YYYY). MMM == Mar, May etc. #backend

- [x]  6> The blue bar “Narrative” in the Other Info tab must be removed. #frontend

- [x] 7> In “Review and Submit” tab the card “Narrative must be renamed to  “Other Info”

- [x] 8 > “Draft” column must be removed from the “Progress Report” page.

- [x] 9> Tooltip must be added to the PD/SSFA ref number link on the Progress  Reports page (programme documents list already has this tooltip it seems) when mouse hover. #frontend

- [x] 10> PD/SSFA ref no. column must be the first column on the Progress Report page. It should not be a link, but should have a tooltip providing the title of the programme document. #frontend

- [ ] 11> ~Align or modify the PD details page as per the below mockup screen, some details are missing on the test environment. https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016131/comments/81120142 #backend (make sure api has all the data) #frontend~ moved to #448

- [x] 12> The following filters should be multiselect: (Programme documents: PD/SSFA Status Report), (Progress: Report Status, Report Type), (Indicators: PD Status, PD) #backend #frontend

- [x] 13> Remove the "draft" column from the "Progress report" page. Dupe of 8>? #frontend

- [ ] ~14> PD/SSFA Ref no must be the first column on the Progress Report page. The 2nd should be the Reports name (cf. table below 13, replacing the “view report” or “enter data” field). #frontend~ moved to #448

- [ ] ~15> DO NOT WORK ON THIS FOR NOW: The calculation method tab should be moved from being a PD tab to being a tab in the progress report data entry screen (consistent with initial specifications) .... OR ..... come up with a solution mock up to make it clear to the user the existence of the calculation method tab, as currently this is a hidden feature that nobody will know about.~ moved to #448

- [ ] ~16> User must have an ability to add one file attachment to the reports. Add a one-off API endpoint to make this upload, and make sure the GET request exposes the upload as well. #backend #frontend~ moved to #448

- [ ] ~17> DO NOT WORK ON THIS FOR NOW: On the indicators page, in the drilldown if the indicator has cluster then the 2 tables must display the current cluster and UNICEF reports, If the indicator has only UNICEF indicator then the tables must display the current and previous progress reports, the overall status must be removed in both the scenarios.~ moved to #448

**Other:** 

- [x] Remove “narrative” in blue bar and make the card not have a title.

- [x] Ability to sort the columns on the Progress reports page.

- [x] Enable sorting for `/api/unicef/<workspace_id>/progress-reports/`

- [x] PD > individual PD > tab Reports https://www.evernote.com/l/AgQpTiuU2dJG8JCcBQef-iBQGIGeO9GW6mg doesn't show total number of results

- [x] in 'Indicators' changing filter while having one or more indicators opened doesn't work properly: the title of indicator gets updated while info inside stays the same. Closing and opening it again fixes it. Should filtering close opened indicator details?

- [x] #447

**Comment by rkrupinski** [comment]
@dfryta 

Regarding

> Enable sorting for /api/unicef/<workspace_id>/progress-reports/

Use `/api/cluster/<response_plan_id>/cluster-activity-list/` as a reference.

**Comment by n1207n** [comment]
Above Misc. changes on IP reporting are updated based on Dec 1st, 2017 change request docs.

**Comment by rkrupinski** [comment]
@n1207n according to https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016131/comments/81120142 , we need to add:

* "In response to an HRP"
* "$ disbursements to date (%)"

to `/api/unicef/<workspace_id>/programme-document/`. The latter needs to be a float within `<0, 1>` range.

**Comment by rkrupinski** [comment]
Filters don't seem to work with the `foo%2Cbar%2Cbaz` value format.

**Comment by rkrupinski** [comment]
@n1207n See my comment on 11) + I'm gonna need some clarification in 1)

**Comment by n1207n** [comment]
@rkrupinski,

For #1, we need to check in with PMP mockup and possibly get insights from there. My understanding is that they want to align how the title is displayed with PMP side.

For #11, `In response to HRP` is on hold at the moment. The logic for Disbursements to date (%) is not sure for me yet. My speculation is that it is an amount from total budget subtracted with Funds received. But, I'll be pinging Rob for the calculation method for disbursements. Therefore, don't work for #11 at the moment.

For #14, ProgressReport never had a name or label field. I'm guessing the label `Reports` should be in 2nd column on the Progress Report list page.

In addition, I have made some changes regarding ProgressReport Attachment GET request. Instead of getting the file url info as JSON response, you'll be redirected to file download immediately. In other words, by calling GET request on ProgressReport Attachment API, the file download will start. If ProgressReport doesn't have attachment, then it'll be 304 response as a 404 NotFound redirect.

**Comment by n1207n** [comment]
Hey @robertavram,

I'm hoping for you to chime in for clarifying the calculation on Disbursements to date from this mockup: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016131

My speculation is that Disbursement is an amount from total budget subtracted with Funds received to date. Let me know if this is a valid calculation logic for disbursements to date in PD. Thanks.

**Comment by n1207n** [comment]
@rkrupinski,

Update on #14 task:

As part of the duel reporting requirements, ProgressReport will have to have a report number, and this may constitute the name for ProgressReport. You can imagine seeing ProgressReport 1 on SQR 1, ProgressReport 2 on SQR 2, and so on.

For now, let's hold off on this until we starts working on duel reporting or have it hardcoded for the time being.

**Comment by rkrupinski** [comment]
Hardcoded for now.
