### ISSUE TITLE
PDF/XLS Miscellaneous bugs

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#487]
Regarding PDF export for

http://prp.tivixlabs.com/app/EG/ip-reporting/indicators?pd_statuses=Act&page_size=10&page=1&blueprint__title=17

http://prp.tivixlabs.com/api/unicef/36/programme-document/indicators/?pd_statuses=Act&page_size=10&page=1&blueprint__title=17&export=pdf

- [x] Location progress and Previous location progress values should be switched

- [x] We are showing too many locations for each indicators. There is excess data

- [x] We don't know what this indicator is pointing to on indicators webpage (example: LLO)

Regarding Excel export https://docs.google.com/spreadsheets/d/1CdXunmlFc9f0dWidEE63QuUD9Z_0oA5ovejA5B33FbM/edit?usp=sharing

- [x] Each Row is location table per indicator report per indicator

We should have 24 and only have 10

-------------
- [x] XLS not working for 4 + 5
sent links via slack

- [x] Small item. For single progress report page, i have an attachment. I know we won't show it but should we have a checkmark or yes if there is one. Right now we have a '----' even though there is an attachment

-[x] for pd on #7, we need to add we need to add 'Achieved' since it was a column just added. 

- [ ] Maciej test with Seth #7 and 6 excel

- [x] #5 need to make sure reporting period is accurate

- [x] #7 we have 9,995 %. It should be 9995 in pdf

**Comment by maciej-jaworski** [comment]
Part of the issue of duplicated rows was that same location can have multiple data entries with single indicator report (schema allows it and fakedata generates it like that). I've fixed the fakedata script (directly on develop), schema fix is commented out since enabling it requires wiping the db and creating new data.
